name: conda-build
channels:
  - conda-forge
dependencies:
  - python =3.11.*
  - conda-build
  - conda-tree
  - conda-verify
  - conda-libmamba-solver =24.9.* # 24.11 can't handle wildcard like "- mpi4py =*_derecho"
