{% set name = "mpi4jax" %}
{% set version_env = environ.get('MPI4JAX_VERSION', '0.5.4') %}

package:
  name: {{ name|lower }}
  version: '{{ version_env }}'

source:
   - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version_env }}.tar.gz
   - path: ../profile.d/modules.sh

build:
  number: 1000 # high priortity over other matches at same version
  string: {{ environ.get('NCAR_HOST') }}_cuda12_py{{ PY_VER }}_{{ PKG_BUILDNUM }}

  # we're really abusing conda-build here.  This package will only work
  # on Derecho with cray-mpich - therefore it will have many dependent
  # shared libraries outside the conda-build source tree.  That's OK,
  # if distasteful.  Allow it.
  host_runpath_whitelist:
    - '/opt/cray/*'
    - '/glade/u/apps/*'

  missing_dso_whitelist:
    - '*/libcublas.so.*'
    - '*/libcublasLt.so.*'
    - '*/libcuda*.so.*'
    - '*/libcudnn.so.*'
    - '*/libcufft.so.*'
    - '*/libcupti.so.*'
    - '*/libcurand.so.*'
    - '*/libcusolver.so.*'
    - '*/libcusparse.so.*'
    - '*/libfabric.so.*'
    - '*/libmpi_*.so*'
    - '*/libnccl.so.*'
    - '*/libnvToolsExt.so.*'
    - '*/libnvrtc.so.*'
    - '*/libpals.so.*'
    - '*/libpmi*.so.*'
    - '*/libpthread.so.0'
    - '/lib64/ld-linux-x86-64.so.2'
    - '/lib64/libc.so.6'
    - '/lib64/libdl.so.2'
    - '/lib64/libgcc_s.so.1'
    - '/lib64/libm.so.6'
    - '/lib64/librt.so.1'
    - '/usr/lib64/libgomp.so.1'
    - '/usr/lib64/libnuma.so.1'
    - '/usr/lib64/libstdc++.so.6'

requirements:
  build:
    - python
    - cython
    - mpi4py =*=derecho*
    - jaxlib ==0.4.38=derecho*
    - jax ==0.4.38=derecho*

  run:
    - python
    - numpy
    - mpi4py =*=derecho*
    - jaxlib ==0.4.38=derecho*
    - jax ==0.4.38=derecho*
    - libgcc >=12
    - libstdcxx >=12

test:
  imports:
    - mpi4jax

about:
  home: https://github.com/mpi4jax/mpi4jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: MPI support for JAX
  description: |
    Zero-copy MPI communication of JAX arrays, for turbo-charged HPC applications in Python ⚡
  doc_url: https://mpi4jax.readthedocs.io
  dev_url: https://github.com/mpi4jax/mpi4jax
