{% set version = "1.7.1" %}
{% set build = 1 %}

{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: libmesh
  version: {{ version }}

source:
  url: https://github.com/libMesh/libmesh/releases/download/v{{ version }}/libmesh-{{ version }}.tar.bz2
  #sha256: 4eb1ec04c1a8988bd524f71f8d7d980dc1853d5be8791c0f19f3c09eef71fdd2

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version == "None"]
  run_exports:
    - {{ pin_subpackage('libmesh', max_pin='x.x') }}
    - libmesh * {{ optim }}_{{ scalar }}_*                       # [cuda_compiler_version == "None"]
  track_features:
    - libmesh_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - sed
    - grep
    - install
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - {{ mpi }}
    - petsc =3.17.*
    - hdf5
    - boost <=1.85*
  run:
    - {{ mpi }}
    - {{ pin_compatible('petsc', min_pin='x', max_pin='x') }}
    - hdf5

# test:
#   requires:
#     - pkg-config
#     - make
#     - {{ compiler('c') }}
#     - {{ compiler('cxx') }}
#     - {{ compiler('fortran') }}
#   files:
#     - tests/ex1.c
#     - tests/ex1f.F90
#     - tests/testdlopen.c
#     - tests/makefile
#   commands:
#     - pkg-config --validate PETSc
#     - pkg-config --cflags PETSc
#     - pkg-config --libs PETSc

# about:
#   home: https://www.mcs.anl.gov/petsc/
#   summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
#   license: BSD-2-Clause
#   license_file: LICENSE
#   license_family: BSD
#   dev_url: https://gitlab.com/petsc/petsc
#   doc_url: https://petsc.org/release/docs/manual/

# extra:
#   recipe-maintainers:
#     - jan-janssen
#     - dalcinl
#     - minrk
#     - davidbrochart
#     - SylvainCorlay
#     - martinRenou
#     - matthiasdiener
#     - stefanozampini
